apiVersion: v1
kind: Service
metadata:
  name: webnodb
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

