apiVersion: v1
kind: Service
metadata:
  name: webdb
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
