apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
