apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: {{ .Release.Namespace }}
data:
  MONGODB_HOSTNAME: {{ .Values.mongodb.hostname }}
  MONGODB_PORT: {{ .Values.mongodb.port | quote }}