apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.webdb.replicas }}
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: {{ .Values.webdb.image }}
        ports:
        - containerPort: {{ .Values.webdb.port }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: MONGODB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGODB_HOSTNAME
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGODB_PORT