apiVersion: v1
kind: Service
metadata:
  name: webnodb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.webnodb.port }}