apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: fodediouf/webdb:3.0
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database
              key: port
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
