apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: fdiouf # Remplacez par votre namespace
  labels:
    app: webnodb
spec:
  type: ClusterIP
  ports:
  - port: 80  # Le port sur lequel le service écoute
    targetPort: 5000  # Le port sur lequel le conteneur écoute
  selector:
    app: webnodb